const { Router } = require("express");
// const auth =require("../middleware/auth.js";
const auth = require("../middleware/auth.js");
// const roleCheck =require("../middleware/roleCheck.js";
const profileController = require("../controllers/users.controller.js");
const upload = require("../controllers/image.controller");
const router = Router();
router.get("/details", auth,profileController.userProfile);
router.post("/profile", auth, profileController.insert);
router.put("/profile_update", auth, profileController.userUpdate);
router.put("/update_image_profile", auth,upload.upload.single("imgurl"), profileController.blog);
module.exports = router;
